project:
  type: website
  output-dir: docs

website:
  title: "Yutaka Horita"
  site-url: https://yutakahorita.github.io/
  description: "堀田結孝(Yutaka Horita)のページ"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "Home"
      - section: "English"
        contents:
          - Research_En.qmd
          - CV_En.qmd
      - section: "Japanese"
        contents:
          - Research_JP.qmd
          - CV_Jp.qmd
          - MISC.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

